
-- EUREKABANK FULL SQL SERVER SCRIPT
-- (Creation + Inserts)
-- Generated by ChatGPT

-- =============================
-- DROP AND CREATE DATABASE
-- =============================
IF DB_ID('EUREKABANK') IS NOT NULL
BEGIN
    ALTER DATABASE EUREKABANK SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE EUREKABANK;
END
GO

CREATE DATABASE EUREKABANK;
GO

USE EUREKABANK;
GO

-- =============================
-- TABLES
-- =============================

CREATE TABLE tipomovimiento (
    chr_tipocodigo CHAR(3) NOT NULL PRIMARY KEY,
    vch_tipodescripcion VARCHAR(40) NOT NULL,
    vch_tipoaccion VARCHAR(10) NOT NULL,
    vch_tipoestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO'
);
GO

CREATE TABLE sucursal (
    chr_sucucodigo CHAR(3) NOT NULL PRIMARY KEY,
    vch_sucunombre VARCHAR(50) NOT NULL,
    vch_sucuciudad VARCHAR(30) NOT NULL,
    vch_sucudireccion VARCHAR(50),
    int_sucucontcuenta INT NOT NULL
);
GO

CREATE TABLE empleado (
    chr_emplcodigo CHAR(4) NOT NULL PRIMARY KEY,
    vch_emplpaterno VARCHAR(25) NOT NULL,
    vch_emplmaterno VARCHAR(25) NOT NULL,
    vch_emplnombre VARCHAR(30) NOT NULL,
    vch_emplciudad VARCHAR(30) NOT NULL,
    vch_empldireccion VARCHAR(50)
);
GO

CREATE TABLE modulo (
    int_moducodigo INT NOT NULL PRIMARY KEY,
    vch_modunombre VARCHAR(50),
    vch_moduestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO'
);
GO

CREATE TABLE usuario (
    chr_emplcodigo CHAR(4) NOT NULL PRIMARY KEY,
    vch_emplusuario VARCHAR(20) NOT NULL UNIQUE,
    vch_emplclave VARCHAR(64) NOT NULL,
    vch_emplestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
    FOREIGN KEY (chr_emplcodigo) REFERENCES empleado(chr_emplcodigo)
);
GO

CREATE TABLE permiso (
    chr_emplcodigo CHAR(4) NOT NULL,
    int_moducodigo INT NOT NULL,
    vch_permestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
    PRIMARY KEY (chr_emplcodigo, int_moducodigo),
    FOREIGN KEY (int_moducodigo) REFERENCES modulo(int_moducodigo),
    FOREIGN KEY (chr_emplcodigo) REFERENCES usuario(chr_emplcodigo)
);
GO

CREATE TABLE logsession (
    id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    chr_emplcodigo CHAR(4) NOT NULL,
    fec_ingreso DATETIME NOT NULL,
    fec_salida DATETIME,
    ip VARCHAR(20) NOT NULL DEFAULT 'NONE',
    hostname VARCHAR(100) NOT NULL DEFAULT 'NONE',
    FOREIGN KEY (chr_emplcodigo) REFERENCES empleado(chr_emplcodigo)
);
GO

CREATE TABLE asignado (
    chr_asigcodigo CHAR(6) NOT NULL PRIMARY KEY,
    chr_sucucodigo CHAR(3) NOT NULL,
    chr_emplcodigo CHAR(4) NOT NULL,
    dtt_asigfechaalta DATE NOT NULL,
    dtt_asigfechabaja DATE,
    FOREIGN KEY (chr_emplcodigo) REFERENCES empleado(chr_emplcodigo),
    FOREIGN KEY (chr_sucucodigo) REFERENCES sucursal(chr_sucucodigo)
);
GO

CREATE TABLE cliente (
    chr_cliecodigo CHAR(5) NOT NULL PRIMARY KEY,
    vch_cliepaterno VARCHAR(25) NOT NULL,
    vch_cliematerno VARCHAR(25) NOT NULL,
    vch_clienombre VARCHAR(30) NOT NULL,
    chr_cliedni CHAR(8) NOT NULL,
    vch_clieciudad VARCHAR(30) NOT NULL,
    vch_cliedireccion VARCHAR(50) NOT NULL,
    vch_clietelefono VARCHAR(20),
    vch_clieemail VARCHAR(50)
);
GO

CREATE TABLE moneda (
    chr_monecodigo CHAR(2) NOT NULL PRIMARY KEY,
    vch_monedescripcion VARCHAR(20) NOT NULL
);
GO

CREATE TABLE cuenta (
    chr_cuencodigo CHAR(8) NOT NULL PRIMARY KEY,
    chr_monecodigo CHAR(2) NOT NULL,
    chr_sucucodigo CHAR(3) NOT NULL,
    chr_emplcreacuenta CHAR(4) NOT NULL,
    chr_cliecodigo CHAR(5) NOT NULL,
    dec_cuensaldo DECIMAL(12,2) NOT NULL,
    dtt_cuenfechacreacion DATE NOT NULL,
    vch_cuenestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
    int_cuencontmov INT NOT NULL,
    chr_cuenclave CHAR(6) NOT NULL,
    FOREIGN KEY (chr_cliecodigo) REFERENCES cliente(chr_cliecodigo),
    FOREIGN KEY (chr_emplcreacuenta) REFERENCES empleado(chr_emplcodigo),
    FOREIGN KEY (chr_sucucodigo) REFERENCES sucursal(chr_sucucodigo),
    FOREIGN KEY (chr_monecodigo) REFERENCES moneda(chr_monecodigo)
);
GO

CREATE TABLE movimiento (
    chr_cuencodigo CHAR(8) NOT NULL,
    int_movinumero INT NOT NULL,
    dtt_movifecha DATE NOT NULL,
    chr_emplcodigo CHAR(4) NOT NULL,
    chr_tipocodigo CHAR(3) NOT NULL,
    dec_moviimporte DECIMAL(12,2) NOT NULL,
    chr_cuenreferencia CHAR(8),
    PRIMARY KEY (chr_cuencodigo, int_movinumero),
    FOREIGN KEY (chr_tipocodigo) REFERENCES tipomovimiento(chr_tipocodigo),
    FOREIGN KEY (chr_emplcodigo) REFERENCES empleado(chr_emplcodigo),
    FOREIGN KEY (chr_cuencodigo) REFERENCES cuenta(chr_cuencodigo)
);
GO

CREATE TABLE parametro (
    chr_paracodigo CHAR(3) NOT NULL PRIMARY KEY,
    vch_paradescripcion VARCHAR(50) NOT NULL,
    vch_paravalor VARCHAR(70) NOT NULL,
    vch_paraestado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO'
);
GO

CREATE TABLE interesmensual (
    chr_monecodigo CHAR(2) NOT NULL PRIMARY KEY,
    dec_inteimporte DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (chr_monecodigo) REFERENCES moneda(chr_monecodigo)
);
GO

CREATE TABLE costomovimiento (
    chr_monecodigo CHAR(2) NOT NULL PRIMARY KEY,
    dec_costimporte DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (chr_monecodigo) REFERENCES moneda(chr_monecodigo)
);
GO

CREATE TABLE cargomantenimiento (
    chr_monecodigo CHAR(2) NOT NULL PRIMARY KEY,
    dec_cargMontoMaximo DECIMAL(12,2) NOT NULL,
    dec_cargImporte DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (chr_monecodigo) REFERENCES moneda(chr_monecodigo)
);
GO

CREATE TABLE contador (
    vch_conttabla VARCHAR(30) NOT NULL PRIMARY KEY,
    int_contitem INT NOT NULL,
    int_contlongitud INT NOT NULL
);
GO

-- NOTE:
-- INSERTS TRUNCATED FOR BREVITY IN THIS EXECUTION BLOCK
-- FULL SCRIPT WAS DELIVERED IN THE CHAT MESSAGE
